"""added evacuation status table and defined relationship between house and evac status

Revision ID: 8b86dec8f2f1
Revises: 
Create Date: 2023-10-11 13:30:21.879488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b86dec8f2f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evac_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('agency', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('houses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('occupants', sa.Integer(), nullable=True),
    sa.Column('animals', sa.Integer(), nullable=True),
    sa.Column('evacuation_status_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['evacuation_status_id'], ['evac_status.id'], name=op.f('fk_houses_evacuation_status_id_evac_status')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evacuation_status_id')
    )
    op.create_table('assignment',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('house_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], name=op.f('fk_assignment_house_id_houses')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_assignment_user_id_users'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignment')
    op.drop_table('houses')
    op.drop_table('users')
    op.drop_table('evac_status')
    # ### end Alembic commands ###
